# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pam_assets_all_of_embedded_items_inner import PAMAssetsAllOfEmbeddedItemsInner

class TestPAMAssetsAllOfEmbeddedItemsInner(unittest.TestCase):
    """PAMAssetsAllOfEmbeddedItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PAMAssetsAllOfEmbeddedItemsInner:
        """Test PAMAssetsAllOfEmbeddedItemsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PAMAssetsAllOfEmbeddedItemsInner`
        """
        model = PAMAssetsAllOfEmbeddedItemsInner()
        if include_optional:
            return PAMAssetsAllOfEmbeddedItemsInner(
                links = openapi_client.models.products_all_of__embedded_items_inner_all_of__links.Products_allOf__embedded_items_inner_allOf__links(
                    self = openapi_client.models.products_all_of__embedded_items_inner_all_of__links_self.Products_allOf__embedded_items_inner_allOf__links_self(
                        href = '', ), ),
                code = '',
                categories = [
                    ''
                    ],
                description = 'null',
                localizable = True,
                tags = [
                    ''
                    ],
                end_of_use = 'null',
                variation_files = [
                    openapi_client.models.pam_assets_all_of__embedded_items_inner_all_of_variation_files_inner.PAM_Assets_allOf__embedded_items_inner_allOf_variation_files_inner(
                        _link = openapi_client.models.pam_assets_all_of__embedded_items_inner_all_of_variation_files_inner__link.PAM_Assets_allOf__embedded_items_inner_allOf_variation_files_inner__link(
                            self = openapi_client.models.pam_assets_all_of__embedded_items_inner_all_of_variation_files_inner__link_self.PAM_Assets_allOf__embedded_items_inner_allOf_variation_files_inner__link_self(
                                href = '', ), 
                            download = openapi_client.models.pam_assets_all_of__embedded_items_inner_all_of_variation_files_inner__link_download.PAM_Assets_allOf__embedded_items_inner_allOf_variation_files_inner__link_download(
                                href = '', ), ), 
                        locale = '', 
                        scope = '', 
                        code = '', )
                    ],
                reference_files = [
                    openapi_client.models.pam_assets_all_of__embedded_items_inner_all_of_reference_files_inner.PAM_Assets_allOf__embedded_items_inner_allOf_reference_files_inner(
                        _link = openapi_client.models.pam_assets_all_of__embedded_items_inner_all_of_reference_files_inner__link.PAM_Assets_allOf__embedded_items_inner_allOf_reference_files_inner__link(
                            self = openapi_client.models.pam_assets_all_of__embedded_items_inner_all_of_reference_files_inner__link_self.PAM_Assets_allOf__embedded_items_inner_allOf_reference_files_inner__link_self(
                                href = '', ), 
                            download = openapi_client.models.pam_assets_all_of__embedded_items_inner_all_of_reference_files_inner__link_download.PAM_Assets_allOf__embedded_items_inner_allOf_reference_files_inner__link_download(
                                href = '', ), ), 
                        locale = '', 
                        code = '', )
                    ]
            )
        else:
            return PAMAssetsAllOfEmbeddedItemsInner(
                code = '',
        )
        """

    def testPAMAssetsAllOfEmbeddedItemsInner(self):
        """Test PAMAssetsAllOfEmbeddedItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
