# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.products2 import Products2

class TestProducts2(unittest.TestCase):
    """Products2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Products2:
        """Test Products2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Products2`
        """
        model = Products2()
        if include_optional:
            return Products2(
                links = openapi_client.models.reference_entities_all_of__links.Reference_Entities_allOf__links(
                    self = openapi_client.models.products_all_of__links_self.Products_allOf__links_self(
                        href = '', ), 
                    first = openapi_client.models.products_all_of__links_first.Products_allOf__links_first(
                        href = '', ), 
                    next = openapi_client.models.products_all_of__links_next.Products_allOf__links_next(
                        href = '', ), ),
                embedded = openapi_client.models.product_uuids_all_of__embedded.Product_uuids_allOf__embedded(
                    items = [
                        ''
                        ], )
            )
        else:
            return Products2(
        )
        """

    def testProducts2(self):
        """Test Products2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
