# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_products_uuid401_response import GetProductsUuid401Response

class TestGetProductsUuid401Response(unittest.TestCase):
    """GetProductsUuid401Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProductsUuid401Response:
        """Test GetProductsUuid401Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetProductsUuid401Response`
        """
        model = GetProductsUuid401Response()
        if include_optional:
            return GetProductsUuid401Response(
                code = 56,
                message = ''
            )
        else:
            return GetProductsUuid401Response(
        )
        """

    def testGetProductsUuid401Response(self):
        """Test GetProductsUuid401Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
