# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.family_list import FamilyList

class TestFamilyList(unittest.TestCase):
    """FamilyList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FamilyList:
        """Test FamilyList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FamilyList`
        """
        model = FamilyList()
        if include_optional:
            return FamilyList(
                links = openapi_client.models.products_all_of__embedded_items_inner_all_of__links.Products_allOf__embedded_items_inner_allOf__links(
                    self = openapi_client.models.products_all_of__embedded_items_inner_all_of__links_self.Products_allOf__embedded_items_inner_allOf__links_self(
                        href = '', ), ),
                code = '',
                attribute_as_label = '',
                attribute_as_image = 'null',
                attributes = [
                    ''
                    ],
                attribute_requirements = openapi_client.models.families_all_of__embedded_items_inner_all_of_attribute_requirements.Families_allOf__embedded_items_inner_allOf_attribute_requirements(
                    channel_code = [
                        ''
                        ], ),
                labels = openapi_client.models.families_all_of__embedded_items_inner_all_of_labels.Families_allOf__embedded_items_inner_allOf_labels(
                    locale_code = '', )
            )
        else:
            return FamilyList(
                code = '',
                attribute_as_label = '',
        )
        """

    def testFamilyList(self):
        """Test FamilyList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
