# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.asset_all_of_embedded_items_inner import AssetAllOfEmbeddedItemsInner

class TestAssetAllOfEmbeddedItemsInner(unittest.TestCase):
    """AssetAllOfEmbeddedItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetAllOfEmbeddedItemsInner:
        """Test AssetAllOfEmbeddedItemsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetAllOfEmbeddedItemsInner`
        """
        model = AssetAllOfEmbeddedItemsInner()
        if include_optional:
            return AssetAllOfEmbeddedItemsInner(
                links = openapi_client.models.products_all_of__embedded_items_inner_all_of__links.Products_allOf__embedded_items_inner_allOf__links(
                    self = openapi_client.models.products_all_of__embedded_items_inner_all_of__links_self.Products_allOf__embedded_items_inner_allOf__links_self(
                        href = '', ), ),
                code = '',
                values = openapi_client.models.asset_all_of__embedded__items_inner_all_of_values.Asset_allOf__embedded__items_inner_allOf_values(
                    attribute_code = [
                        openapi_client.models.asset_all_of__embedded__items_inner_all_of_values_attribute_code_inner.Asset_allOf__embedded__items_inner_allOf_values_attributeCode_inner(
                            channel = '', 
                            locale = '', 
                            data = openapi_client.models.data.data(), 
                            _links = openapi_client.models._links._links(), 
                            linked_data = openapi_client.models.linked_data.linked_data(), )
                        ], ),
                created = '',
                updated = ''
            )
        else:
            return AssetAllOfEmbeddedItemsInner(
                code = '',
        )
        """

    def testAssetAllOfEmbeddedItemsInner(self):
        """Test AssetAllOfEmbeddedItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
