# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.published_product_list import PublishedProductList

class TestPublishedProductList(unittest.TestCase):
    """PublishedProductList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublishedProductList:
        """Test PublishedProductList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublishedProductList`
        """
        model = PublishedProductList()
        if include_optional:
            return PublishedProductList(
                links = openapi_client.models.products_all_of__embedded_items_inner_all_of__links.Products_allOf__embedded_items_inner_allOf__links(
                    self = openapi_client.models.products_all_of__embedded_items_inner_all_of__links_self.Products_allOf__embedded_items_inner_allOf__links_self(
                        href = '', ), ),
                identifier = '',
                enabled = True,
                family = 'null',
                categories = [
                    ''
                    ],
                groups = [
                    ''
                    ],
                values = openapi_client.models.published_product_list_all_of_values.PublishedProductList_allOf_values(
                    attribute_code = [
                        openapi_client.models.published_product_list_all_of_values_attribute_code.PublishedProductList_allOf_values_attributeCode(
                            scope = '', 
                            locale = '', 
                            data = openapi_client.models.product_model_list_all_of_values_data.ProductModelList_allOf_values_data(), )
                        ], ),
                associations = openapi_client.models.published_products_all_of__embedded_items_inner_all_of_associations.Published_products_allOf__embedded_items_inner_allOf_associations(
                    association_type_code = openapi_client.models.published_products_all_of__embedded_items_inner_all_of_associations_association_type_code.Published_products_allOf__embedded_items_inner_allOf_associations_associationTypeCode(
                        groups = [
                            ''
                            ], 
                        products = [
                            ''
                            ], 
                        product_models = [
                            ''
                            ], ), ),
                quantified_associations = None,
                created = '',
                updated = ''
            )
        else:
            return PublishedProductList(
                identifier = '',
        )
        """

    def testPublishedProductList(self):
        """Test PublishedProductList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
