# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_assets_code200_response import GetAssetsCode200Response

class TestGetAssetsCode200Response(unittest.TestCase):
    """GetAssetsCode200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAssetsCode200Response:
        """Test GetAssetsCode200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAssetsCode200Response`
        """
        model = GetAssetsCode200Response()
        if include_optional:
            return GetAssetsCode200Response(
                code = '',
                values = openapi_client.models.asset_all_of__embedded__items_inner_all_of_values.Asset_allOf__embedded__items_inner_allOf_values(
                    attribute_code = [
                        openapi_client.models.asset_all_of__embedded__items_inner_all_of_values_attribute_code_inner.Asset_allOf__embedded__items_inner_allOf_values_attributeCode_inner(
                            channel = '', 
                            locale = '', 
                            data = openapi_client.models.data.data(), 
                            _links = openapi_client.models._links._links(), 
                            linked_data = openapi_client.models.linked_data.linked_data(), )
                        ], ),
                created = '',
                updated = ''
            )
        else:
            return GetAssetsCode200Response(
                code = '',
        )
        """

    def testGetAssetsCode200Response(self):
        """Test GetAssetsCode200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
