# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_after_pagination import SearchAfterPagination

class TestSearchAfterPagination(unittest.TestCase):
    """SearchAfterPagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchAfterPagination:
        """Test SearchAfterPagination
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchAfterPagination`
        """
        model = SearchAfterPagination()
        if include_optional:
            return SearchAfterPagination(
                links = openapi_client.models.reference_entities_all_of__links.Reference_Entities_allOf__links(
                    self = openapi_client.models.products_all_of__links_self.Products_allOf__links_self(
                        href = '', ), 
                    first = openapi_client.models.products_all_of__links_first.Products_allOf__links_first(
                        href = '', ), 
                    next = openapi_client.models.products_all_of__links_next.Products_allOf__links_next(
                        href = '', ), )
            )
        else:
            return SearchAfterPagination(
        )
        """

    def testSearchAfterPagination(self):
        """Test SearchAfterPagination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
