# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_reference_entity_records_code200_response import GetReferenceEntityRecordsCode200Response

class TestGetReferenceEntityRecordsCode200Response(unittest.TestCase):
    """GetReferenceEntityRecordsCode200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetReferenceEntityRecordsCode200Response:
        """Test GetReferenceEntityRecordsCode200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetReferenceEntityRecordsCode200Response`
        """
        model = GetReferenceEntityRecordsCode200Response()
        if include_optional:
            return GetReferenceEntityRecordsCode200Response(
                code = '',
                values = openapi_client.models.reference_entity_record_all_of__embedded_items_inner_all_of_values.Reference_entity_record_allOf__embedded_items_inner_allOf_values(
                    attribute_code = [
                        openapi_client.models.reference_entity_record_all_of__embedded_items_inner_all_of_values_attribute_code_inner.Reference_entity_record_allOf__embedded_items_inner_allOf_values_attributeCode_inner(
                            channel = '', 
                            locale = '', 
                            data = openapi_client.models.data.data(), )
                        ], ),
                created = 'null',
                updated = 'null'
            )
        else:
            return GetReferenceEntityRecordsCode200Response(
                code = '',
        )
        """

    def testGetReferenceEntityRecordsCode200Response(self):
        """Test GetReferenceEntityRecordsCode200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
