# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.product_values_value_inner import ProductValuesValueInner

class TestProductValuesValueInner(unittest.TestCase):
    """ProductValuesValueInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductValuesValueInner:
        """Test ProductValuesValueInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductValuesValueInner`
        """
        model = ProductValuesValueInner()
        if include_optional:
            return ProductValuesValueInner(
                locale = '',
                data = openapi_client.models.data.data(),
                linked_data = openapi_client.models.products_all_of__embedded_items_inner_all_of_values_value_inner_linked_data.Products_allOf__embedded_items_inner_allOf_values_value_inner_linked_data(
                    attribute = '', 
                    code = '', 
                    labels = openapi_client.models.labels.labels(), ),
                attribute_type = '',
                reference_data_name = ''
            )
        else:
            return ProductValuesValueInner(
        )
        """

    def testProductValuesValueInner(self):
        """Test ProductValuesValueInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
