# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.products1_all_of_embedded_items_inner_all_of_associations_association_type_code import Products1AllOfEmbeddedItemsInnerAllOfAssociationsAssociationTypeCode

class TestProducts1AllOfEmbeddedItemsInnerAllOfAssociationsAssociationTypeCode(unittest.TestCase):
    """Products1AllOfEmbeddedItemsInnerAllOfAssociationsAssociationTypeCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Products1AllOfEmbeddedItemsInnerAllOfAssociationsAssociationTypeCode:
        """Test Products1AllOfEmbeddedItemsInnerAllOfAssociationsAssociationTypeCode
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Products1AllOfEmbeddedItemsInnerAllOfAssociationsAssociationTypeCode`
        """
        model = Products1AllOfEmbeddedItemsInnerAllOfAssociationsAssociationTypeCode()
        if include_optional:
            return Products1AllOfEmbeddedItemsInnerAllOfAssociationsAssociationTypeCode(
                groups = [
                    ''
                    ],
                products = [
                    ''
                    ],
                product_models = [
                    ''
                    ]
            )
        else:
            return Products1AllOfEmbeddedItemsInnerAllOfAssociationsAssociationTypeCode(
        )
        """

    def testProducts1AllOfEmbeddedItemsInnerAllOfAssociationsAssociationTypeCode(self):
        """Test Products1AllOfEmbeddedItemsInnerAllOfAssociationsAssociationTypeCode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
