# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.asset_list_all_of_values_attribute_code import AssetListAllOfValuesAttributeCode

class TestAssetListAllOfValuesAttributeCode(unittest.TestCase):
    """AssetListAllOfValuesAttributeCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetListAllOfValuesAttributeCode:
        """Test AssetListAllOfValuesAttributeCode
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetListAllOfValuesAttributeCode`
        """
        model = AssetListAllOfValuesAttributeCode()
        if include_optional:
            return AssetListAllOfValuesAttributeCode(
                channel = '',
                locale = '',
                data = openapi_client.models.asset_list_all_of_values_data.AssetList_allOf_values_data(),
                links = openapi_client.models.asset_list_all_of_values__links.AssetList_allOf_values__links(),
                linked_data = openapi_client.models.asset_list_all_of_values_linked_data.AssetList_allOf_values_linked_data()
            )
        else:
            return AssetListAllOfValuesAttributeCode(
        )
        """

    def testAssetListAllOfValuesAttributeCode(self):
        """Test AssetListAllOfValuesAttributeCode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
