# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.category_update import CategoryUpdate

class TestCategoryUpdate(unittest.TestCase):
    """CategoryUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CategoryUpdate:
        """Test CategoryUpdate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CategoryUpdate`
        """
        model = CategoryUpdate()
        if include_optional:
            return CategoryUpdate(
                code = '',
                parent = 'null',
                updated = '',
                position = 56,
                labels = openapi_client.models.categories_all_of__embedded_items_inner_all_of_labels.Categories_allOf__embedded_items_inner_allOf_labels(
                    locale_code = '', ),
                values = [
                    openapi_client.models.post_categories_request_values_inner.post_categories_request_values_inner(
                        data = '', 
                        locale = '', 
                        channel = '', 
                        attribute_code = '', )
                    ]
            )
        else:
            return CategoryUpdate(
                code = '',
        )
        """

    def testCategoryUpdate(self):
        """Test CategoryUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
