# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.published_products import PublishedProducts

class TestPublishedProducts(unittest.TestCase):
    """PublishedProducts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublishedProducts:
        """Test PublishedProducts
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublishedProducts`
        """
        model = PublishedProducts()
        if include_optional:
            return PublishedProducts(
                links = openapi_client.models.products_all_of__links.Products_allOf__links(
                    self = openapi_client.models.products_all_of__links_self.Products_allOf__links_self(
                        href = '', ), 
                    first = openapi_client.models.products_all_of__links_first.Products_allOf__links_first(
                        href = '', ), 
                    previous = openapi_client.models.products_all_of__links_previous.Products_allOf__links_previous(
                        href = '', ), 
                    next = openapi_client.models.products_all_of__links_next.Products_allOf__links_next(
                        href = '', ), ),
                current_page = 56,
                embedded = openapi_client.models.published_products_all_of__embedded.Published_products_allOf__embedded(
                    items = [
                        openapi_client.models.published_products_all_of__embedded_items_inner.Published_products_allOf__embedded_items_inner()
                        ], )
            )
        else:
            return PublishedProducts(
        )
        """

    def testPublishedProducts(self):
        """Test PublishedProducts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
