# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.products_all_of_links import ProductsAllOfLinks

class TestProductsAllOfLinks(unittest.TestCase):
    """ProductsAllOfLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductsAllOfLinks:
        """Test ProductsAllOfLinks
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductsAllOfLinks`
        """
        model = ProductsAllOfLinks()
        if include_optional:
            return ProductsAllOfLinks(
                var_self = openapi_client.models.products_all_of__links_self.Products_allOf__links_self(
                    href = '', ),
                first = openapi_client.models.products_all_of__links_first.Products_allOf__links_first(
                    href = '', ),
                previous = openapi_client.models.products_all_of__links_previous.Products_allOf__links_previous(
                    href = '', ),
                next = openapi_client.models.products_all_of__links_next.Products_allOf__links_next(
                    href = '', )
            )
        else:
            return ProductsAllOfLinks(
        )
        """

    def testProductsAllOfLinks(self):
        """Test ProductsAllOfLinks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
