# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.product_models_all_of_embedded_items_inner_all_of_values import ProductModelsAllOfEmbeddedItemsInnerAllOfValues

class TestProductModelsAllOfEmbeddedItemsInnerAllOfValues(unittest.TestCase):
    """ProductModelsAllOfEmbeddedItemsInnerAllOfValues unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductModelsAllOfEmbeddedItemsInnerAllOfValues:
        """Test ProductModelsAllOfEmbeddedItemsInnerAllOfValues
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductModelsAllOfEmbeddedItemsInnerAllOfValues`
        """
        model = ProductModelsAllOfEmbeddedItemsInnerAllOfValues()
        if include_optional:
            return ProductModelsAllOfEmbeddedItemsInnerAllOfValues(
                attribute_code = [
                    openapi_client.models.product_models_all_of__embedded_items_inner_all_of_values_attribute_code_inner.Product_Models_allOf__embedded_items_inner_allOf_values_attributeCode_inner(
                        scope = '', 
                        locale = '', 
                        data = openapi_client.models.data.data(), 
                        linked_data = openapi_client.models.product_models_all_of__embedded_items_inner_all_of_values_attribute_code_inner_linked_data.Product_Models_allOf__embedded_items_inner_allOf_values_attributeCode_inner_linked_data(
                            attribute = '', 
                            code = '', 
                            labels = openapi_client.models.labels.labels(), ), )
                    ]
            )
        else:
            return ProductModelsAllOfEmbeddedItemsInnerAllOfValues(
        )
        """

    def testProductModelsAllOfEmbeddedItemsInnerAllOfValues(self):
        """Test ProductModelsAllOfEmbeddedItemsInnerAllOfValues"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
