# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.patch_reference_entity_records200_response_inner import PatchReferenceEntityRecords200ResponseInner

class TestPatchReferenceEntityRecords200ResponseInner(unittest.TestCase):
    """PatchReferenceEntityRecords200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchReferenceEntityRecords200ResponseInner:
        """Test PatchReferenceEntityRecords200ResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchReferenceEntityRecords200ResponseInner`
        """
        model = PatchReferenceEntityRecords200ResponseInner()
        if include_optional:
            return PatchReferenceEntityRecords200ResponseInner(
                code = '',
                status_code = 56,
                message = ''
            )
        else:
            return PatchReferenceEntityRecords200ResponseInner(
        )
        """

    def testPatchReferenceEntityRecords200ResponseInner(self):
        """Test PatchReferenceEntityRecords200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
