# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AssetListAllOfValuesAttributeCode(BaseModel):
    """
    AssetListAllOfValuesAttributeCode
    """ # noqa: E501
    channel: Optional[StrictStr] = Field(default=None, description="Channel code of the asset attribute value")
    locale: Optional[StrictStr] = Field(default=None, description="Locale code of the asset attribute value")
    data: Optional[Dict[str, Any]] = Field(default=None, description="Asset attribute value. See <a href='/concepts/asset-manager.html#the-data-format'>the `data` format</a> section for more details.")
    links: Optional[Dict[str, Any]] = Field(default=None, description="Related links for the `media file` attribute values. See <a href='/concepts/asset-manager.html#the-_links-format'>the `_links` format</a> section for more details.", alias="_links")
    linked_data: Optional[Dict[str, Any]] = Field(default=None, description="Linked data for the `media link` attribute values. See <a href='/concepts/asset-manager.html#the-linked_data-format'>the `linked_data` format</a> section for more details.")
    __properties: ClassVar[List[str]] = ["channel", "locale", "data", "_links", "linked_data"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssetListAllOfValuesAttributeCode from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssetListAllOfValuesAttributeCode from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "channel": obj.get("channel"),
            "locale": obj.get("locale"),
            "data": obj.get("data"),
            "_links": obj.get("_links"),
            "linked_data": obj.get("linked_data")
        })
        return _obj


